# Generated by Django 4.1.7 on 2023-09-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('min_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
